### ISSUE TITLE
[feedback] Allow users to edit the docs pages

### ISSUE THREAD

**Issue by e111077** [lit/lit.dev#681] opened 2022-02-02 02:35 UTC
Create a feature that will allow users to make a PR with edits directly from each page. e.g. link out to the associated github file

**Comment by abdonrd** [comment] 2022-02-02 09:06
Regarding this...

If you want to use the GitHub issues, I see one project using this nice way.

There is `Report bug` button:

<img width="239" alt="Screenshot 2022-02-02 at 10 03 55" src="https://user-images.githubusercontent.com/1007051/152124074-36bf5540-9741-476f-b656-2d17467f9d3e.png">

With this URL:
https://github.com/directus/directus/issues/new?template=bug_report.yml&directus-version=9.5.0&node-version=16.13.0&operating-system=macOS+Monterey+%2812%29

As you can see in the URL, they populate it with default values. So there is pre-populated info in the issue:

<img width="506" alt="Screenshot 2022-02-02 at 10 05 55" src="https://user-images.githubusercontent.com/1007051/152124228-fa69c8ca-e9d6-4a91-82a9-7d06bb1d8ab9.png">

**Comment by aomarks** [comment] 2022-02-02 17:20
Dupe of https://github.com/lit/lit.dev/issues/450

**Comment by e111077** [comment] 2022-02-03 21:32
closing in favor of #450

**Closed** 2022-02-03 21:32 UTC
