### ISSUE TITLE
JS example on the first page more verbose than TS version

### ISSUE THREAD

**Issue by LAC-Tech** [lit/lit.dev#397] opened 2021-06-29 05:36 UTC
Javascript version could just be:

```javascript
import {html, css, LitElement} from 'lit';

export class SimpleGreeting extends LitElement {
  static styles = css`p { color: blue }`;

  static properties = {
    name: {type: String}
  }

  constructor() {
    super();
    this.name = 'Somebody';
  }

  render() {
    return html`<p>Hello, ${this.name}!</p>`;
  }
}

customElements.define('simple-greeting', SimpleGreeting);
```
Styles and properties don't need to be getter functions, do they? This saves 4 lines and looks a bit nicer.

I get that it's still not as nice as the TS version without decorators, but no need to make it more long-winded than it needs to be.

**Comment by arthurevans** [comment] 2021-07-10 02:10
Thanks for opening the issue. Yeah, this is unfortunate. If I understand correctly, the issue is that Safari didn't support static class fields until very recently (a couple of months ago, according to [caniuse.com](https://caniuse.com/?search=static%20class%20fields)). Our current docs say that you shouldn't need to compile stuff for Safari 12+, but if you use static class fields, you will need to compile.

This seems like something we may want to update in the near future as the usage share for Safari 12 goes down. Because the static class fields do look nicer and they work fine with this one annoying caveat--that you'll need to compile them out for some fairly new browsers.

**Comment by AndrewJakubowicz** [comment] 2021-09-17 00:41
Thank you! This has now been addressed by https://github.com/lit/lit.dev/pull/495.

Homepage JS example is now shorter.

**Closed by AndrewJakubowicz** 2021-09-17 00:41 UTC
